### ISSUE TITLE
Running Experiments Locally

### ISSUE THREAD

**Issue by pratik98** [ahmedcs/REFL#1]
probably, stupid question.  
is it possible run the experiments [albeit with lower number of workers/clients ] on resource-constraint local machine with one GPU?  [mac or windows]

**Comment by ahmedcs** [comment]
@pratik98 hello thanks for trying out REFL. yes, you can try out CPU/Nvidia-based GPUs on your desktop. For modern MACs with MPS GPU-support, there are slight changes in the conda libraries that need to be installed. Please let me know if you need further help.
